version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: node1
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.8.0
    container_name: filebeat
    depends_on:
      - elasticsearch
    volumes:
      - filebeat:/usr/share/filebeat/data
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/pipelines:/usr/share/logstash/config/pipelines:ro
      - ./filebeat/pipelines/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - /home/alkp/projects/microservices/ads/log:/var/log/ads:ro  # TODO путь к логам ads микросервиса
      - /home/alkp/projects/microservices/geo/log:/var/log/geo:ro  # TODO путь к логам geo микросервиса
      - /home/alkp/projects/microservices/auth/log:/var/log/auth:ro  # TODO путь к логам auth микросервиса
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
  prom:
    image: prom/prometheus
    container_name: prom
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3007:3000
    volumes:
      - grafana:/var/lib/grafana
volumes:
  rabbitmq:
  filebeat:
  elasticsearch:
  prometheus:
  grafana:
